# Generated by Django 3.0.7 on 2020-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201024_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkshare',
            name='course',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT')], max_length=50, null=True),
        ),
    ]
