# Generated by Django 3.0.7 on 2020-10-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201025_0138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacherProfile',
        ),
    ]
