# Generated by Django 3.0.7 on 2020-10-25 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201025_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
