# Generated by Django 3.0.7 on 2020-10-25 12:19

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201025_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('data', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
