# Generated by Django 3.0.7 on 2020-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_noticedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticedata',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
