# Generated by Django 3.0.7 on 2020-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201025_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticedata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
