# Generated by Django 3.0.7 on 2020-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201025_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
