# Generated by Django 3.0.7 on 2020-10-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201026_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpaper',
            old_name='user',
            new_name='studentid',
        ),
        migrations.AlterField(
            model_name='answerpaper',
            name='marks',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
