# Generated by Django 3.0.7 on 2020-10-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='course',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT')], max_length=50, null=True),
        ),
    ]
