# Generated by Django 3.0.7 on 2020-10-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_questionpaper_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationlinkshare',
            name='expired',
        ),
    ]
