# Generated by Django 3.0.7 on 2020-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_registrationlinkshare_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationlinkshare',
            name='key',
            field=models.TextField(default='', null=True),
        ),
    ]
