# Generated by Django 3.0.7 on 2020-11-02 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_customuser_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='pyq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT')], max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('link', models.TextField(default='')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
